### ISSUE TITLE
Documentation required

### ISSUE THREAD

**Issue by iu2frl** [lora-aprs/LoRa_APRS_iGate#113]
A small wiki would be very useful to better tunes parameters such as "digi active" or "digi beacon" and 
the ftp settings

**Comment by peterus** [comment]
you are right! the documentation is still very bad and I finally need to work on it.
Today i had some time and create this wiki page: https://github.com/lora-aprs/LoRa_APRS_iGate/wiki/Configuration

Feel free to ask questions if something is not clear to you!

In the next days I will create on page with a step by step guide how to install LoRa APRS iGate the best on any platform.

**Comment by iu2frl** [comment]
That's more than enough to begin!
