### ISSUE TITLE
No RX with 21.35.0-develop

### ISSUE THREAD

**Issue by DB2FM** [lora-aprs/LoRa_APRS_iGate#114]
With the newest develop-Branch of today my iGate didn't receive anymore. 
Wet back to master and everything works as expected. 

**Board name:**
- PoE-iGate

**Comment by peterus** [comment]
thanks for this ticket! this information is very important! i will take a look into this 😉

**Comment by peterus** [comment]
@DB2FM i reverted a big change, please re-test and revert. thanks!

**Comment by DB2FM** [comment]
@peterus Hi Peter,

I don’t see develop branch anymore. There are only three branches: master, http_config and python_test_framework.
Which one should I try?

**Comment by peterus** [comment]
@DB2FM by accident i deleted the branch yesterday. i could revert the deletion and have setup a protection for the branch.
please try again with the developer branch.

**Comment by DB2FM** [comment]
@peterus Hi Peter,
When I download ZIP in branch develop I get master.zip of 01.09.2021...

**Comment by peterus** [comment]
@DB2FM just checked it: the download zip is always pointing to the master branch for me even if i change the branch to another one.

**Comment by DB2FM** [comment]
@peterus Same for me.

**Comment by peterus** [comment]
```
git clone https://github.com/lora-aprs/LoRa_APRS_iGate.git
git checkout develop
```

**Comment by DB2FM** [comment]
RX does work again :)

> Am 20.09.2021 um 07:48 schrieb Peter Buchegger ***@***.***>:
> 
> git checkout develop
