### ISSUE TITLE
add support to SX126X Lora chips.

### ISSUE THREAD

**Issue by GabeHC** [lora-aprs/LoRa_APRS_iGate#122]
I made a [ESP32 Lora board](https://easyeda.com/GabeH/esp32-lora-aprs) with E22 module, am now trying to program it as a iGate/Digi.  Currently it works good with RadioLib. I have very little knowledge regarding APRS, and AX25. your project is the most robust  I have ever tried. if you can add SX126X to this project. it can really save me a lot of works. 

Thanks!

**Comment by peterus** [comment]
please wait for https://github.com/lora-aprs/LoRa_APRS_iGate/pull/183
I have soon time to check the PR.
