### ISSUE TITLE
platformio error building igate

### ISSUE THREAD

**Issue by rampa069** [lora-aprs/LoRa_APRS_iGate#123]
**Describe the bug**
Had a lot of errors (wifi related) building the project

**To Reproduce**
1. Clone repo
2. build
**Expected behavior**
 Firmware built.

**Desktop (please complete the following information):**
 - OS:  KDE neon
 - PlatformIO Version: 
 - Firmware Version: 

**Board name:**
- helltek V2

Fixed adding:

 lib_ignore = WiFi101

to platformIO.ini

**Comment by peterus** [comment]
@rampa069 thanks for creating this ticket. please add a complete logfile of your issue to the ticket.
