### ISSUE TITLE
Please document the packet format

### ISSUE THREAD

**Issue by cfr34k** [lora-aprs/LoRa_APRS_iGate#126]
I'm currently trying to develop a custom tracker firmware for the Lilygo T-Echo that I'd like to make compatible with this LoRa APRS iGate firmware. Unfortunately, it seems like there is no documentation about the LoRa packet format yet.

Could you please add a section describing the packet format to the Wiki?

---

I have already tried to determine the format from the source code, but have not yet been able to deliver a packet to any iGate out there.

So far, I managed to extract the following rules from the code. Can you please confirm or correct my findings?

- There is a packet header `<\xff\x01` (in C string syntax).
- The call signs and path are encoded in regular ASCII, like `DL0xxx>GPS,WIDE2-2`. I’m unsure because normal APRS/AX.25 left-shifts the ASCII values by one bit and uses the free bit as a special flag.
- Path and data are separated by `:`.
- The data is a normal APRS data field as defined in [the APRS specification](http://www.aprs.org/doc/APRS101.PDF), chapter 5.
- There is no additional checksum, only the CRC calculated by the LoRa modem.

When I follow these rules, I get a packet like the following (in C string syntax):

```
<\xff\x01DL0xxx>GPS,WIDE2-2:/193653h4800.00N/01100.00E[/A=001000 T-Echo test
```

Is this a valid packet?

**Comment by peterus** [comment]
Hi @cfr34k!
sorry for the late answer!
the LoRa header is indeed <\xff\x01 (historical reason).
than the normal ASCI APRS protocol is used like from the APRS-IS servers. No checksum, just the one from the LoRa modem.
correct, this is a valid package.

if you have more questions, please reopen the ticket.
