### ISSUE TITLE
Wifi hotspot for configuration (captive portal / webinterface)

### ISSUE THREAD

**Issue by do1das** [lora-aprs/LoRa_APRS_iGate#144]
Hi, this is just a low priority suggestion / feature request:

**Is your feature request related to a problem? Please describe.**
If you want to connect to a different wifi (and dont have access to your old one), you need to reconfigure and reupload the file system image via visual studio and usb.

**Describe the solution you'd like**
It would be nice to press a button pattern to force the device in "hotspot mode" and change wifi settings (and maybe other settings) via a webinterface/captive portal, e.g. like this: https://github.com/Juerd/ESP-WiFiSettings
This could also be an alternative for the initial setup.

vy 73 de Daniel, do1das

**Comment by peterus** [comment]
duplicated #77
