### ISSUE TITLE
Starting Lora Failed

### ISSUE THREAD

**Issue by iw9grl** [lora-aprs/LoRa_APRS_iGate#153]
**Describe the bug**
Hi
me and a friend of mine bought the board : Wemos LILYGO TTGO LORA SX1278 ESP32

the board unfortunately didn't have an UART connection but anyway we solved this issue with a workaround using an external UART-TTL converter.

We are able to upload the firmware correctly but we receive this message : 

![lora failed](https://user-images.githubusercontent.com/16877668/151136405-d5c4476d-ee93-4afb-a48d-9545ddb5eca6.jpeg)

It seems that SX1278 is not available, but the chip is on board as you can see :   

![loramodem](https://user-images.githubusercontent.com/16877668/151136647-d4bda11b-c401-485d-8516-835238badf70.JPG)

another thing is that the oled display didn't poweron

 - OS: Win10
 - PlatformIO Version: last available
 - Firmware Version:  last available

thank you
73 de IW9GRL

**Comment by iw9hfs** [comment]
I'm the friend :-) 73 IW9HFS Francesco.ciao

**Comment by peterus** [comment]
Hi all,
sorry for the big delay.
Try to erase the board and reflash it again. Try to get the log output when you first startup the board to see if the board finding is successful.
73 de OE5BPA

**Comment by iw9grl** [comment]
> Hi all, sorry for the big delay. Try to erase the board and reflash it again. Try to get the log output when you first startup the board to see if the board finding is successful. 73 de OE5BPA

Hi

thank you for the answer, we will try with your suggestion . In case of other fault I will copy/paste the log here !

73 de IW9GRL
