### ISSUE TITLE
LoRa-APRS (POE from OE5BPA) stops receiving after some hours or days...

### ISSUE THREAD

**Issue by RudiOnTheAir** [lora-aprs/LoRa_APRS_iGate#155]
Hi
After a few hours to days, no more Lora packets are received. Only after a reset it is receiving again. I'm running the IGATE software  a module with POE supply from OE5BPA. It seems that only the modem stopps working. The regular reports to aprs.fi go further out. Only there is no reception. The OLED shows "Modem ok".

But when the beacon counter ist going to 00:00, the OLED shows an error as shown in the picture. At the same time, the terminal shows: 
`D            TaskRouter.cpp   81 : [15:19:57] DB0ET-L4>APLG01:=5324.35NL00700.95E&LoRa iGATE Lighthouse Campen@Emsmouth, Info: https://db0et.de/`
![20220214_153159](https://user-images.githubusercontent.com/47517341/153892233-2b170fba-ff7a-4df3-aef0-ba303cc38076.jpg)

What could be wrong. And why not direct after restart.??

**Comment by peterus** [comment]
@RudiOnTheAir please recheck with current firmware version and enable syslog for easier checking
