### ISSUE TITLE
IGate GPS not working

### ISSUE THREAD

**Issue by N1obu** [lora-aprs/LoRa_APRS_iGate#187]
Using a TBeam v1.0.  Enabled GPS in the config file. IGate doesn't obtain a GPS position.

**Comment by m1geo** [comment]
Try flashing [this code](https://github.com/lora-aprs/TTGO-T-Beam_GPS-reset) in case a previous project has taken the GPS out of NEMA. Monitor the serial console, and you'll see what is going on.

**Comment by N1obu** [comment]
That did the trick.  The TBeam's are very "sensitive" to firmware changes.  I had to totally erase the flash, then reset the GPS.  Finally the IGate would use/display the GPS info on APRS.FI
