### ISSUE TITLE
Prevent OLED burn in

### ISSUE THREAD

**Issue by HelmiBeh** [lora-aprs/LoRa_APRS_iGate#190]
After some month of operation, some of the OLED shows burn in effects, if the same text is displayed with high brightness. To prevent this, it should be possible to lower brightness or the display is inverted after a couple of hours.

**Comment by peterus** [comment]
you can set the `display` option `always_on` to false, in this case the display will just be turned on in special cases.
https://github.com/lora-aprs/LoRa_APRS_iGate/blob/a599edabe29adea1ed0b08aff77cee505f5a4d14/data/is-cfg.json#L55
