### ISSUE TITLE
Decrease frequency of NTPTask

### ISSUE THREAD

**Issue by Mane76** [lora-aprs/LoRa_APRS_iGate#195]
By checking the syslog (either local or using syslog.lora-aprs.info) it is visible that NTPTask is performed each minute. On the one hand this produces unneeded traffic locally but also produces unneeded traffic to the syslog Server.

To reproduce simply check the syslog, all versions are affected

The expected behaviour would be to start the NTPTask less frequent, e.g. each 6 hours. The internal RTC of the lora board is also capable of this.

Solution: 
Please change the value in "lib/NTPClient/NTPclient.h", line 20
from default value 60000 to e.g. 21600000.

 `unsigned long _updateInterval = 21600000;  // In ms
`

Thank you
Manfred

**Comment by peterus** [comment]
thanks for the pull request!
