### ISSUE TITLE
Omit sending OTA progress to syslog

### ISSUE THREAD

**Issue by Mane76** [lora-aprs/LoRa_APRS_iGate#196]
By checking the syslog (either local or using syslog.lora-aprs.info) it is visible that OTATask is is sending the start, the progress, the end or the error of an OTA event. OTA start, end and error or only single lines, but progress is 9 (!) pages of unneeded information to syslog.lora-aprs.info. This produces unneeded traffic locally but also produces unneeded traffic to the syslog Server. Currently there are 200+ LoRa_APRS_iGates logging to syslog.lora-aprs.info, the number is steadily increasing.

To reproduce simply check the syslog, all versions are affected.

The expected behaviour would be to omit sending the OTA progress to syslog.

Solution:
delete the lines 26, 27 and 28 in src/TaskOTA.cpp

Thank you
Manfred

**Comment by peterus** [comment]
thanks!
