### ISSUE TITLE
Dynamic position of iGate

### ISSUE THREAD

**Issue by trinler007** [lora-aprs/LoRa_APRS_iGate#202]
Hi,

I would like to install an iGate in my motorhome. It would be great to determine the position of the iGate via GPS instead of configuring it statically.

In the is-cfg.json there is the parameter "use_gps" which is not described in detail in connection with a T-Beam v1 but the function doesn't seem to have any effect.

Is this possible or is this a planned feature?

Thanks, 73
Markus, DO5MTK

**Comment by peterus** [comment]
use_gps is exactly whatyou should use.
please recheck with tracker firmware and if needed perform a gps reset.
