### ISSUE TITLE
maybe path "TCPIP*" is missing in beacons

### ISSUE THREAD

**Issue by dahuafschmied** [lora-aprs/LoRa_APRS_iGate#206]
I'm not sure but shouldn't the path "TCPIP*" be used for IP forwarding packets?
Compared to other gateways, the LoRa iGate lacks this.

Just look at the raw packets at OE5XPM-10 at https://aprs-map.info/.
I have added the path and the icon appears.

**Comment by peterus** [comment]
"TCPIP*" should be used in case you want to forward from one server to another.

the current implementation was done with the aprs spec.
