### ISSUE TITLE
codingRate4

### ISSUE THREAD

**Issue by Vitaliy86** [lora-aprs/LoRa_APRS_iGate#233]
Why codingRate4 = 5

Maybe need used codingRate4 = 7 ?

**Comment by Mane76** [comment]
The coding rate describes the ratio of actual data to error-correcting data added. 
The higher the value (valid from 5 to 8) the higher the amount of error-correcting data is added to the payload. The header is always transmitted with coding rate 4/8.

As iGate (in RX and explicit mode) there is no influence by this parameter. The iGate uses the value sent by the tracker.
As Digi (in TX and explicit mode) it will send as per this parameter. The higher the value the longer takes the TX time.

In theory this provides better performance but has longer TX time. Therefore 4/5 is the recommended parameter.
