### ISSUE TITLE
Destination APLG01, path Type Error Data

### ISSUE THREAD

**Issue by blacksocket** [lora-aprs/LoRa_APRS_iGate#276]
Hello,

I have compiled and uploaded the latest firmware and during the start I am getting the error "Destination APLG01, path Type Error Data" like on the below image. Then it can connect to aprs.fi and the Lora Gateway is also visible on the map. However when launch the second device T-Beam v1 board with LORA APRS tracker i can't see any data received by the LORA APRS iGate.

**Expected behavior**
The LORA Tracker should be received by LORA iGate and should be visible in aprs.fi map

**Screenshots**
![335399913_1218601175434317_2981178487874523747_n](https://user-images.githubusercontent.com/13651344/224579508-abe7059b-2882-4991-9e07-5fc875f1e9dc.jpg)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - PlatformIO Version: 3.0.0
 - iGate Firmware Version: v23.6.0
 - Tracker Firmware Version: v22.19.0

**Board name:**
TTGO T-Beam V1.1 ESP32 433 >> iGate
TTGO T-Beam V1.1 ESP32 433 >> Tracker

**Additional context**

I can't see the LED blinking on my tracker device like below . Maybe it is also related to some issues on tracker side but I can't see any errors there.

https://youtu.be/7rNx44RMTtg?t=1985

![image](https://user-images.githubusercontent.com/13651344/224579825-a8be85f6-01aa-4df6-9733-b90489b2453d.png)

**Comment by blacksocket** [comment]
I have found root cause namely there were some connection issues to GPS module. That causing the tracker was not sending the signal. Now it works, so we can close the issue.

**Comment by videobuff** [comment]
Could you explain more in detail what kind of connection issues and what you did to correct them. Soldering ?
I have the same error but iwhen listening on the frequency by a Yeasu FT991A, i do not hear any beacon signals.
