### ISSUE TITLE
Heltec v3 board stuck in boot loop when connected to an USB power supply

### ISSUE THREAD

**Issue by dm5tt** [lora-aprs/LoRa_APRS_iGate#331]
**Describe the bug**
After  flashing the latest ARPS iGate firmware to a Heltec v3 AND connecting it to an USB power supply only the boot logo shows up and then reboots after a few seconds.

This NOT happens when connected to a PC.

(Cross-checked this with a Meshtastic. This  boots up just fine.)

**To Reproduce**

1. Flash latest 'master' firmware
2. Connect device to a USB power supply
3. Have a look at the screen and wait for reboot
 
**Expected behavior**
Boot up normally

**Comment by peterus** [comment]
did you check the power supply if it is producing the 5v correctly? can you try different power supplies? if it is working when connected to pc it will get very hard to debug.

**Comment by dm5tt** [comment]
I checked with three power supplies and several cables. The Meshtastic firmware on that device seems not to cause any problems.

**Comment by peterus** [comment]
thanks for your response! will need to check on my end.

**Comment by dm5tt** [comment]
https://github.com/Heltec-Aaron-Lee/WiFi_Kit_series/issues/159   wild guess, might be related

**Comment by dm5tt** [comment]
I was able to narrow the problem down: The Heltec v3 is having an incredibly bad Wifi antenna. It was looping during the boot process as it wasn't able to get Wifi on my balcony.
