### ISSUE TITLE
compile error (missing files etc.)

### ISSUE THREAD

**Issue by woyteg** [lora-aprs/LoRa_APRS_iGate#338]
Hello. I need help iguring out what is wrong. When I try to compile the files after editing I get this errors. I am not a programmer and have no clue what to do :(

[compile_error.txt](https://github.com/lora-aprs/LoRa_APRS_iGate/files/13402037/compile_error.txt)

**Comment by peterus** [comment]
next time please post the log directly in the ticket, attaching via a link a log is not nice (worms, spam, viruses, etc.)

you where to fast in installing platformio! remove your platformio installation and install it again AND take your time - platformio is doing a lot of stuff in the brackground which need to be finished bevor doing something else.
this should fix your problem.

**Comment by woyteg** [comment]
Using Mac fixed the issue. Thank you
