### ISSUE TITLE
Coordinates Limit

### ISSUE THREAD

**Issue by woyteg** [lora-aprs/LoRa_APRS_iGate#351]
It looks we are unable to enter coordinates which are more than 100. I tried to enter Longitude of -103 and the system changed that to -89.

**Comment by peterus** [comment]
can you post exactly what you are changing in the json file? there is no such limit in the code.

**Comment by woyteg** [comment]
sorry wrong github. Appologies.

**Comment by woyteg** [comment]
Actually I was in the right place. When I try to put coordinates using the web interface, it changes longitude from 103 to 89.
It looks like it doesn't take anything larger than 90. I use decimal values from Google Maps.
