### ISSUE TITLE
KISS TNC functionality

### ISSUE THREAD

**Issue by SQ9MDD** [lora-aprs/LoRa_APRS_iGate#59]
I report the need for KISS-TNC mode for use with APRS applications. 
For example with APRSIS32, APRX or APRSDROID software

I would like to connect DIGI LORA with DIGI APRS in 2m band which works under APRX control, so that data from LORA can be sent directly to APRS bypassing APRS-IS for off-grid operation

**Comment by M0IGA** [comment]
Agree with SQ9MDD we need KISS TNC. It will help to build LoRa based full working DIGIS.

**Comment by SQ2iBK** [comment]
Dears,
We will be very grateful for your help in writing kissTNC.

Kind Regards,
SQ2IBK

**Comment by peterus** [comment]
as there is already a working KISS-TNC implementation from @SQ9MDD  i will close this ticket.
https://github.com/SQ9MDD/TTGO-T-Beam-LoRa-APRS
