### ISSUE TITLE
Bildschirm steht Kopf bei Heltec V1 Board

### ISSUE THREAD

**Issue by whallmann** [lora-aprs/LoRa_APRS_iGate#61]
Mit der Beta Version steht der 0.96 Oled auf dem Kopf.

**Expected behavior**
Drehung um 180 Grad wäre fein.

**Screenshots**
keine notwendig

**Desktop (please complete the following information):**
 - OS: Windows 10
 - PlatformIO Version: Core 5.1.0·Home 3.3.3
 - Firmware Version: 21.04.0-dev

**Board name:**
- China-Nachbau zu Heltec V1

**Additional context**
-nope-

**Comment by peterus** [comment]
closed with https://github.com/lora-aprs/LoRa_APRS_iGate/commit/8cf0c6768321ace66bc7a35b79b60c4397b10ef9
