### ISSUE TITLE
Fehleranzeigen im Display

### ISSUE THREAD

**Issue by whallmann** [lora-aprs/LoRa_APRS_iGate#62]
**Describe the bug**
Beim Booten kommt in eigenen Beacon-Paket im Display der Hinweis "..Type:Error..." sie Foto Nr. ..002

**To Reproduce**
Erste Bake nach dem Bootvorgang

**Expected behavior**
?? Kein ERROR

**Screenshots**
![Peterus_Igate_Beta_002](https://user-images.githubusercontent.com/5610320/106386412-22534b00-63d5-11eb-9b2f-fb91a2be2d99.jpg)

**Desktop (please complete the following information):**
 - OS:  Windows 10 
 - PlatformIO Version: 5.1.0/3.3.3
 - Firmware Version: 21.04.0-dev

**Board name:**
- China Heltec V1

**Additional context**
Damit in Verbindung steht vielleicht auch diese Anzeige einer Gegenstelle mit der Angabe "position without timestamp"
![Peterus_Igate_Beta_001](https://user-images.githubusercontent.com/5610320/106386497-883fd280-63d5-11eb-872f-14316f7b54cb.jpg)

In Pausen wird das Display angezeigt (steht jetzt auf dem Kopf)
![Peterus_Igate_Beta_005](https://user-images.githubusercontent.com/5610320/106386531-b58c8080-63d5-11eb-94d5-553a9e305f61.jpg)

**Comment by peterus** [comment]
i was taking a look on the error message: there is a bug in the aprs decoder library, I will fix it there when i add more features to it. but this information is just on the display, the message format is okay! there is no nedd for a quick fix now! will close this ticket when i updated the library and pushed the new version here.

on the display upside down: i fixed this with ticket #61
