### ISSUE TITLE
No Call-Info in main screen

### ISSUE THREAD

**Issue by aronaut** [lora-aprs/LoRa_APRS_iGate#64]
**Is your feature request related to a problem? Please describe.**
There is no Call Information at the main screen like in the old version.
If you run more iGates in parallel, its nice to see at one sight which iGate it is.

**Describe the solution you'd like**
Call Info in the mai screen.

**Comment by peterus** [comment]
closing with https://github.com/lora-aprs/LoRa_APRS_iGate/commit/38d50cb8012898d90b29590e2375abce7bef3531
