### ISSUE TITLE
WXStation on iGate by BMP/BME280 sensor

### ISSUE THREAD

**Issue by faridfarhan28-zz** [lora-aprs/LoRa_APRS_iGate#66]
Hi, could you add some feature Weather Station by BMP/BME280 sensor on iGate like picture on bellow ?
these name is CWOP APRS. Thanks

![image](https://user-images.githubusercontent.com/37871833/108592488-aaa78900-73a0-11eb-9d24-d52dcc407128.png)

**Comment by faridfarhan28** [comment]
maybe gived optional sensor
BMP/BME280 (temperature/huminity/Aviation QNH Pressure (mbar))
DHT (temperature/Huminity)

**Comment by faridfarhan28** [comment]
CWOP APRS format refrence

http://pond1.gladstonefamily.net/aprswxnet.html

**Comment by peterus** [comment]
It will be as an enhancement listed in my head ;) currently there is more important stuff to fix, thanks for your idea!

**Comment by peterus** [comment]
as I decided I want to focuse on a "simple" but powerful iGate this is no feature which I would like to add.
