### ISSUE TITLE
Asking configuration wiring if i use ESP32-WROM

### ISSUE THREAD

**Issue by faridfarhan28** [lora-aprs/LoRa_APRS_iGate#68]
hi mr.peterus, i would to ask something, do you know how to wiring pin configuration if i use custom device example ESP32 and RA-02 like picture in bellow for gateway ? thanks

![image](https://user-images.githubusercontent.com/37871833/108600172-3aacf900-73c8-11eb-8d34-32a879b73eb5.png)

**Comment by peterus** [comment]
is it possible to get a better picture? i will add this suggestion into the new release which will come up in the next days (currently developer branch).
