### ISSUE TITLE
Implement Base91 and/or mic-e

### ISSUE THREAD

**Issue by peterus** [lora-aprs/LoRa_APRS_iGate#73]
http://www.aprs.org/aprs12/mic-e-examples.txt

**Comment by BD5HTY** [comment]
Hello peterus,
1833net@163.com This is my email address, please contact me if possible, thank you!

**Comment by peterus** [comment]
> Hello peterus,
> This is my email address, please contact me if possible, thank you!

I have the feeling that you are a bot, so i removed your email. if you have questions please write the questions in github. if you will not response in the next 48h i will remove you post.

**Comment by BD5HTY** [comment]
Sorry for any inconveniences caused. I have been looking for your contact information for a long time, but I can't find it. I am from China and I have provided you with a small sponsorship. I would like to provide you with more help regarding the LoRa APRS project. I like this project very much.

Thanks again for your contribution!

73 de BD5HTY

**Comment by peterus** [comment]
Sorry for the confusion! I had the feeling that you where a bot so i was very skeptical about it, I should have just looked up your callsign ;)
you are right! there is not a lot of information to get in contact with me :)
Please write me a email on oe5bpa@gmail.com and I will come back to you as soon as possible.
Thank you very much!

**Comment by BD5HTY** [comment]
Copied, this post can be deleted, thank you very much!

**Comment by dg0tm** [comment]
What is the purpose of it?

All kind of RX packets should passes through the iGate.
