### ISSUE TITLE
is this iGate firmware doesn't seem to be able to receive APRS beacon sent via different LoRa firmware

### ISSUE THREAD

**Issue by dnwk** [lora-aprs/LoRa_APRS_iGate#80]
**Describe the bug**
I just setup my iGate with LoRa_APRS_iGate. 
I make sure Frequency/SF/CR/Bandwidth and SyncWord are matched to the client tracker (I am using https://github.com/sh123/esp32_loraprs for its KISS function).  The APRS packets sent by client doesn't seem to be decoded on the iGate.

**Comment by peterus** [comment]
@dnwk never heard of an issue like this. are the 3 header bytes attached to the message? there are several trackers etc. working with this iGate firmware.
