### ISSUE TITLE
iGate Can't connect to hidden Wifi (hidden SSID)

### ISSUE THREAD

**Issue by yc8nyj** [lora-aprs/LoRa_APRS_iGate#82]
I really like the iGate APRS with this ESP32 ... but when I want to connect to hidden wifi (hidden SSID) ... it can't connection .... even though I have entered the SSID and password ... how to solve it?

**Comment by peterus** [comment]
@yc8nyj after some research i was coming to the conclusion that this is an ESP32/Arduino issue which is not behaving on the Wifi standard. So I can not help you on this issue.
