### ISSUE TITLE
No reconnection to WLAN after lost WLAN connection

### ISSUE THREAD

**Issue by Jup88** [lora-aprs/LoRa_APRS_iGate#88]
When WLAN connection to the iGate gets lost, the iGate doesn't do an automatic re-connection to the WLAN. It stops working and the screen says " booting". 

booting screen:
![image](https://user-images.githubusercontent.com/84144563/118155025-0e79a500-b418-11eb-80c9-7caa14ad76aa.png)

Automatic restart including notification to WLAN would be very appreciated to ensure an 24/7 operation.

Firmware Version: Release v21.14.0

Board: TTGO-t-beam-v1

Peter, it would be great if you could get it fixed. Your work is highly appreciated. We all like your iGate solution :-)

**Comment by peterus** [comment]
Thanks for the ticket.
There are currently a lot of issues with Wifi which i will fix asap!

**Comment by peterus** [comment]
there are a lot of improvements in the last release #96. please check and report again if there are issues :)

**Comment by Jup88** [comment]
Hi Peter,

many, many thanks for updating the iGate Firmware to improve the Wifi
reconnection issues. I have done the update and had no issues so far. I
will give you feedback the next days how it works.

Highly appreciate your pioneers work.

Wish you all the best.

73 de Klaus, DL1ND



Am Do., 24. Juni 2021 um 21:42 Uhr schrieb Peter Buchegger <
***@***.***>:

**Comment by Jup88** [comment]
Hi Peter,

I would like to give you the feedback that WLAN is working very stable now.
In my case 4 weeks without any issues so far.

Thanks for your work.

73 de Klaus DL1ND

Peter Buchegger ***@***.***> schrieb am Do., 24. Juni 2021,
21:42:

**Comment by reinald100** [comment]
Hallo ich bekomme keine Verbindung zum Aprsis  Server.Es steht immer Aprsis not connected.Muss ich in der Fritz Box noch einen Port eventuell freischalten? 
Die WLAN Verbindung geht ohne Probleme.
