### ISSUE TITLE
Rssi & Snr

### ISSUE THREAD

**Issue by ON2ON-HAM** [lora-aprs/LoRa_APRS_iGate#89]
Is there a way that you could show the Rssi and Snr values from an incomming packet from a Tracker ?
73 ON2ON

**Comment by OK1FWG** [comment]
I vote for this enhancement also.

**Comment by do4dhh** [comment]
...that were great

**Comment by f4dvk** [comment]
Would it be possible to add the RSSI and SNR in the frame sent to aprs-is?

Thank you,
Stephane.
