### ISSUE TITLE
Igate Mobile use

### ISSUE THREAD

**Issue by ON2ON-HAM** [lora-aprs/LoRa_APRS_iGate#91]
Low priority but would be a great asset,
The igate has only a static loction entry possible.
It would be great to also have an option, so that the Igate could be used mobile, and the location would come from the
onboard GPS of the board.

If you see this as a possible change, I would love to hear about it ;)

Thanks

ON2ON

**Comment by drtechga** [comment]
I vote for this as well

**Comment by peterus** [comment]
this is already possible with version https://github.com/lora-aprs/LoRa_APRS_iGate/releases/tag/v22.12.0
